title = "Kolors"
baseURL = "https://kwai-kolors.github.io"
languageCode = "en-us"
theme = "ananke"
# resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Kolors"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages
  # [languages.fr]
  #   title = "Ananke Fr"
  #   weight = 2
  #   contentDir = "content/fr"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

# favicon参考： https://ibrights.github.io/post/blog20210527/#:~:text=%E7%82%B9%E5%87%BB%E9%A1%B5%E9%9D%A2%E4%B8%8B%E6%96%B9%E7%9A%84%E7%94%9F%E6%88%90%E6%8C%89%E9%92%AE%E7%94%9F%E6%88%90%E6%88%91%E4%BB%AC%E7%9A%84%E5%9B%BE%E6%A0%87%E5%92%8C%E4%BB%A3%E7%A0%81%E3%80%82%20%E7%94%9F%E6%88%90%E5%AE%8C%E6%88%90%E5%90%8E%EF%BC%8C%E7%82%B9%E5%87%BB%E5%A6%82%E5%9B%BE%E6%89%80%E7%A4%BA%E6%8C%89%E9%92%AE%E4%B8%8B%E8%BD%BD%E5%90%84%E7%B1%BB%E6%A0%BC%E5%BC%8F%E7%9A%84%E5%9B%BE%E6%A0%87%E5%8C%85%EF%BC%8C%E5%86%8D%E5%B0%86%E8%87%AA%E5%8A%A8%E7%94%9F%E6%88%90%E7%9A%84%20HTML%20%E4%BB%A3%E7%A0%81%E5%A4%8D%E5%88%B6%E5%88%B0%E5%89%AA%E8%B4%B4%E6%9D%BF%E3%80%82%20%E4%B9%8B%E5%90%8E%EF%BC%8C%E6%9D%A5%E5%88%B0%20Hugo,%E7%AB%99%E7%82%B9%E7%9A%84%E6%A0%B9%E7%9B%AE%E5%BD%95%EF%BC%8C%E5%B0%86%E5%88%9A%E5%88%9A%E4%B8%8B%E8%BD%BD%E7%9A%84%E5%8E%8B%E7%BC%A9%E5%8C%85%E9%87%8C%E7%9A%84%E6%89%80%E6%9C%89%E6%96%87%E4%BB%B6%E8%A7%A3%E5%8E%8B%E5%88%B0%20%2Fstatic%2F%20%E6%96%87%E4%BB%B6%E5%A4%B9%E4%B8%8B%E3%80%82%20%E7%94%A8%E6%96%87%E6%9C%AC%E7%BC%96%E8%BE%91%E5%99%A8%E6%89%93%E5%BC%80%20%2Flayouts%2Fpartials%2Ffavicon.html%20%E6%96%87%E4%BB%B6%EF%BC%8C%E6%B8%85%E7%A9%BA%E5%8E%9F%E6%9C%89%E4%BB%A3%E7%A0%81%EF%BC%8C%E5%B0%86%E5%88%9A%E5%88%9A%E5%A4%8D%E5%88%B6%E5%88%B0%E4%BB%A3%E7%A0%81%E7%B2%98%E8%B4%B4%E8%BF%9B%E5%8E%BB%EF%BC%8C%E4%BF%9D%E5%AD%98%E5%B9%B6%E9%80%80%E5%87%BA%E3%80%82
[params]
  text_color = ""
  author = ""
  favicon = "favicon/favicon.ico"
  site_logo = "images/logo_thumbnail.png"
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "github"
url = "https://github.com/Kwai-Kolors"
